name: auto-fetch-runner

on:
  push:
    branches:
      - main
  pull_request_target:
  
  schedule:
    - cron: '0 0 * * *' # Schedule to run at midnight (UTC time)

jobs:
  auto-fetch-runner:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.head_ref }}

    - name: Run Fetch AWS IP Script
      run: |
        chmod +x fetch-aws-ip-ranges.sh
        ./fetch-aws-ip-ranges.sh

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "[skip ci] - updated"
        # Add the following line to provide the required authentication value
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
